baseURL = "https://www.maxiaotong.site/"
languageCode = "zh-CN"
title = "马晓彤的导航"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = "八荒山人"

[params]
  author = "八荒山人"
  description = "使用Webstack Hugo的导航站"
  # 使用svg代替favicon.png
  svgFavicon = "/favicon.svg"
  # 用于Open Graph和Twitter Card
  images = ['/images/Preview.png']

[params.search]
  enable = true

# 网站所有权验证
[params.verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""
  so = ""
  sogou = ""